version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssword123
    ports:
        - 27017:27017
    volumes:
        - mongodata:/var/lib/mongodb/data
volumes:
  mongodata: