version: '3.1'

services:
  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
     - PGADMIN_DEFAULT_EMAIL=dev@domain.com
     - PGADMIN_DEFAULT_PASSWORD=P@ssword123
    ports:
        - 8888:80
    volumes:
        - pgadmin:/var/lib/pgadmin 
 
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=P@ssword123
    ports:
        - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssword123
    ports:
        - 27017:27017
    volumes:
        - mongodata:/var/lib/mongodb/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672

volumes:
  mongodata:
  pgadmin:    
  pgdata: